blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog_view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import ClientListView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, \
    IndexView, MailingListView, MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDelete, \
    MailingCreateView, MailingDetailView, MailingUpdateView, LogListView

app_name = MailingConfig.name


class MailingDeleteView:
    pass


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_view'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_view'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('messages/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<int:pk>/delete/', MessageDelete.as_view(), name='message_delete'),
    path('log/log_list/', LogListView.as_view(), name='log_list'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, UserUpdateView, generate_new_password

''' LogoutView, RegisterView, UserUpdateView, set_new_password, \
    UserConfirmEmailView, \
    UserConfirmedView, password_reset, UserConfirmationSentView, UserListView, UserUpdateManagerView
    '''

app_name = UsersConfig.name


urlpatterns = [

    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("profile/gen_password", generate_new_password, name="gen_password"),
]

'''path("logout/", LogoutView.as_view(), name="logout"),
    
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("profile/set_password", set_new_password, name="set_password"),
    path('password_reset/', password_reset, name='password_reset'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('edit_user/<int:pk>/', UserUpdateManagerView.as_view(), name='edit_user'),'''

mailing/models.py
from django.utils import timezone

from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True }


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='email')
    fullname = models.CharField(max_length=100, verbose_name='полное имя')
    comment = models.TextField(max_length=250, verbose_name='комментарий', **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return f'{self.fullname} - {self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ['email']


class Message(models.Model):
    message_subject = models.CharField(max_length=100, verbose_name='тема письма')
    message = models.TextField(verbose_name='cообщение')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец сообщения',**NULLABLE)


    def __str__(self):
        return f'{self.message_subject}: {self.message}'

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"


class Mailing(models.Model):

    frequency_choices = [
        ('daily', 'ежедневно'),
        ('weekly', 'еженедельно'),
        ('monthly', 'ежемесячно')
    ]

    status_choices = [
        ("created", "Создана"),
        ("completed", "Завершена"),
        ("started", "Запущена"),
    ]


    start_time = models.DateTimeField(default=timezone.now, verbose_name='время начала рассылки')
    end_time = models.DateTimeField(**NULLABLE, verbose_name='время окончания рассылки')
    frequency = models.CharField(max_length=50, choices=frequency_choices, verbose_name='периодичность')
    status = models.CharField(max_length=50, choices=status_choices, verbose_name='статус')
    clients = models.ManyToManyField(Client, verbose_name='клиенты')
    is_active = models.BooleanField(default=True, verbose_name='статус активности')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='content')
    last_sent = models.DateTimeField(**NULLABLE, verbose_name='последняя отправка')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец рассылки')



    def __str__(self):
        return f'{self.start_time} , {self.frequency} , {self.status}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'



class Log(models.Model):

    STATUS_CHOICE = (
        ("success", "Успешно"),
        ("failed", "Неуспешно"),
    )
    mailing = models.ForeignKey(Mailing, verbose_name='рассылка', on_delete=models.CASCADE)
    last_attempt = models.DateTimeField(verbose_name='время последней попытки')
    status = models.CharField(max_length=7, choices=STATUS_CHOICE, verbose_name='статус попытки')
    message = models.CharField(max_length=200, verbose_name='сообщение', **NULLABLE)

    def __str__(self):
        return f'{self.mailing} ({self.last_attempt}) - {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

mailing/forms.py
from django import forms
from mailing.models import Mailing, Client, Message

frequency_choices = [
        ('daily', 'ежедневно'),
        ('weekly', 'еженедельно'),
        ('monthly', 'ежемесячно')
    ]

status_choices = [
        ("created", "Создана"),
        ("completed", "Завершена"),
        ("started", "Запущена"),
    ]

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_active":
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('client',)

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, DetailView, UpdateView, DeleteView, CreateView

from blog.models import Blog
from mailing.forms import ClientForm, MessageForm, MailingForm
from mailing.models import Client, Mailing, Message, Log
import random

class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)

class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients_list')

class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:clients_list')

class IndexView(TemplateView):
    """Класс отображения главной страницы сервиса"""

    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'

        # Получение количества рассылок всего
        total_mailings = Mailing.objects.count()
        context['total_mailings'] = total_mailings

        # Получение количества активных рассылок
        active_mailings = Mailing.objects.filter(is_active=True).count()
        context['active_mailings'] = active_mailings

        # Получение количества уникальных клиентов для рассылок
        total_clients = Client.objects.count()
        context['total_clients'] = total_clients


        # Получение всех статей блога
        all_blogs = list(Blog.objects.all())

        if len(all_blogs) >= 3:
            random_blogs = random.sample(all_blogs, 3)
        else:
            random_blogs = all_blogs

        context['random_blogs'] = random_blogs

        return context


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.can_manager_view'):
            return queryset
        return queryset.filter(owner=self.request.user)


class MailingCreateView(LoginRequiredMixin, CreateView):

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class MailingDetailView(DetailView):
    model = Mailing


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs

class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:messages_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.can_manager_view'):
            return queryset
        return queryset.filter(owner=self.request.user)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:messages_list')


class MessageDelete(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:messages_list')

class LogListView(LoginRequiredMixin, ListView):
    model = Log

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.can_manager_view'):
            return queryset
        return queryset.filter(mailing__owner=self.request.user)

mailing/templates/mailing/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сервис рассылок</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="canonical" href="https://bootstrap-4.ru/docs/5.3/examples/headers/">
    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
<header class="p-3 text-bg-success">
    <div class="d-flex flex-column flex-md-row align-items-center p-2 px-md-3">
        <h5 class="my-0 mr-md-auto font-weight-normal">Сервис рассылок</h5>
    </div>
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'mailing:index' %}" class="nav-link px-2 text-prymary">Главная</a></li>
                <li><a href="{% url 'mailing:mailing_list' %}" class="nav-link px-2 text-prymary">Рассылки</a></li>
                <li><a href="{% url 'mailing:message_list' %}" class="nav-link px-2 text-prymary">Сообщения</a></li>
                <li><a href="{% url 'mailing:client_list' %}" class="nav-link px-2 text-prymary">Клиенты</a></li>
                <li><a href="{% url 'mailing:log_list' %}" class="nav-link px-2 text-prymary">Логи рассылки</a></li>
                <li><a href="{% url 'blog:blog_list' %}" class="nav-link px-2 text-prymary">Блог</a></li>
            </ul>
            <div class="text-end">
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-prymary me-2" href="{% url 'users:logout' %}">Выйти</a>
                    <a class="btn btn-warning" href="{% url 'users:profile' %}">Мой профиль</a>
                {% else %}
                    <a class="btn btn-outline-prymary me-2" href="{% url 'users:login' %}">Войти</a>
                    <a class="p-2 btn btn-warning" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
            </div>

        </div>
    </div>
</header>

{% block content %}
{% endblock %}

<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Сервис рассылок
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'mailing:mailing_list' %}">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Полезные статьи</a></li>
                    <li><a class="text-muted" href="#">Защита от SPAM</a></li>
                    <li><a class="text-muted" href="#">Настройки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="{% url 'blog:blog_list' %}" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<br>
<h2 align="center">Удаление клиента</h2>
<div class="container">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Удалить клиента "<b>{{ client.fullname }}</b>"?</p>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
        <br>
        <a href="{% url 'mailing:client_list' %}" class="button">Назад к списку клиентов</a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
    <br>
    <h2 align="center">Просмотр клиента</h2><br><br>
    <div class="row mx-2">
        <div class="col-md-4 mb-3">
        </div>
        <div class="col-md-8 mb-3">
            <p><b>Имя:</b> {{ client.fullname }}</p>
            <p><b>Email:</b> {{ client.email }}</p>
            <p><b>Комментарий:</b><br>{{ client.comment }}</p><br>
            <a href="{% url 'mailing:client_list' %}"
               class="button">Назад к списку клиентов</a>
        </div>
    </div><br><br>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div>
    <div class="row mt-2">
        <div class="col m-2"><br>
        {#    {% if not perms.mail.can_manager_view %}   #}
            <h2 align="center">Список ваших клиентов</h2>
            <br>
            <div class="row mt-2">
                <div class="col m-2">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:client_create' %}">Добавить нового
                        клиента</a>
                </div>
            </div>
            {#   {% else %}                                #}
            <h2 align="center">Клиенты нашего сервиса</h2>
            <br>
            {# {% endif %}                                 #}
            {% if client_list %}
            <br>
            <table class="table">
                <thead>
                <tr class="table-success">
                    <th>№</th>
                    <th>Имя клиента</th>
                    <th>Email клиента</th>
                    <th>Комментарий</th>
                    <th>Действия с клиентом</th>
                </tr>
                </thead>
                <tbody>
                {% for client in client_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ client.fullname }}</td>
                    <td>{{ client.email }}</td>
                    <td>{{ client.comment }}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{% url 'mailing:client_view' client.pk %}"
                               class="btn btn-sm btn-outline-secondary">Посмотреть</a>
         {#                   {% if not perms.mail.can_manager_view %}                                   #}
                            <a href="{% url 'mailing:client_update' client.pk %}"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'mailing:client_delete' client.pk %}"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
         {#                   {% endif %}                                                                #}
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}<br>
            <p align="center">Вы еще ничего не создавали</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <br>
    <h2 align="center">Удаление рассылки</h2>
    <div class="container">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "<b>{{ mailing.message.message_subject }}</b>"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'mail:mailing_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
            <br>
            <a href="{% url 'mail:mailing_list' %}"
               class="button">Назад к списку рассылок</a>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div>
    <div class="row mt-2">
        <div class="col m-2"><br>
{#            {% if not perms.mail.can_manager_view %}     #}
            <h2 align="center">Все ваши рассылки</h2>
            <p align="center">Начните сооздавать вашу первую рассылку с создания нового привлекательного
                сообщения
                и добавления списка получателей</p><br>
            <div class="row mt-2">
                <div class="col m-2">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}">Добавить
                        рассылку</a>
                    <a class="btn btn-outline-primary" href="{% url 'mailing:message_create' %}">Добавить
                        сообщение</a>
                    <a class="btn btn-outline-primary" href="{% url 'mailing:client_create' %}">Добавить
                        клиента</a>
                </div>
            </div>
 {#           {% else %}                                                           #}
            <h2 align="center">Рассылки всех пользователей</h2>
            <br>
            <div class="row mt-2">
                <div class="col m-2">
                    <a class="btn btn-outline-primary" href="#">Список всех
                        пользователей</a>
                </div>
            </div>
   {#         {% endif %}                                    #}
            {% if mailing_list %}
            <br>
            <table class="table table-reflow">
                <thead>
                <tr class="table-success">
                    <th>№</th>
                    <th>Сообщение</th>
                    <th>Начало</th>
                    {# <th>Окончание</th> #}
                    <th>Период</th>
                    <th>Статус</th>
                    <th>Клиенты</th>
                    <th>Действия с рассылками</th>
                </tr>
                </thead>
                <tbody>
                {% for mailing in mailing_list %}
                <tr class="{% if mailing.status == 'created' %}bg-warning
                                   {% elif mailing.status == 'started' %}bg-success
                                   {% elif mailing.status == 'completed' %}bg-danger
                                   {% endif %}">

                    <td>{{ forloop.counter }}</td>
                    <td>{{ mailing.message.message_subject }}</td>
                    <td>{{ mailing.start_time }}</td>
                    <td>{{ mailing.status }}</td>

                    {% if mailing.get_status == 'created' %}
                    <td class="text-black-50">{{ mailing.get_status }}</td>
                    {% elif mailing.get_status == 'started' %}
                    <td class="text-primary">{{ mailing.get_status }}</td>
                    {% elif mailing.get_status == 'completed' %}
                    <td class="text-success">{{ mailing.get_status }}</td>
                    {% endif %}
                    <td>
                        {% for client in mailing.client.all %}
                        {{ client.email }}<br>
                        {% endfor %}
                    </td>
                    <td>
                        {% if not perms.mail.can_manager_view %}
                        <div class="btn-group">
                            {% if mailing.get_status == 'created' %}
                            <a href="{% url 'mailing:send_mailing' mailing.pk %}"
                               class="btn btn-sm btn-outline-success">Отправить</a>
                            {% endif %}
                            <a href="{% url 'mailing:mailing_view' mailing.pk %}"
                               class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                            <a href="{% url 'mailing:mailing_update' mailing.pk %}"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'mailing:delete_mailing' mailing.pk %}"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                            {% else %}
                            <div class="btn-group">
                                <a href="{% url 'mailing:mailing_view' mailing.pk %}"
                                   class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                {% if mailing.is_active %}
                                <a href="#"
                                   class="btn btn-sm btn-outline-danger">Остановить</a>
                                {% else %}
                                <a href="#"
                                   class="btn btn-sm btn-outline-success">Начать</a>
                                {% endif %}
                                <a href="#"
                                   class="btn btn-sm btn-outline-primary">Пользователь</a>
                                {% endif %}
                            </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}<br>
            <p align="center">Нет доступных рассылок</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mail/base.html' %}
{% block content %}
<br>
<h2 align="center">Удаление сообщения</h2>
<div class="container">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Удалить сщщбщение "<b>{{ message.message_subject }}</b>"?</p>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'mail:cmessage_list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
        <br>
        <a href="{% url 'mail:message_list' %}"
           class="button">Назад к списку сообщений</a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mail/base.html' %}
{% block content %}
    <br>
    <h2 align="center">Просмотр сообщения</h2><br><br>
    <div class="row mx-2">
        <div class="col-md-4 mb-3">

        </div>
        <div class="col-md-8 mb-3">
            <p><b>Cообщение:</b> {{ message.message_subject }}</p>
            <p><b>Содержание:</b><br>{{ message.message }}</p>
            <br>
            <a align="center " href="{% url 'mail:message_list' %}"
               class="button">Назад к списку сообщений</a>
        </div>
    </div><br><br>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div>
        <div class="row mt-2">
            <div class="col m-2"><br>
                {% if not perms.mail.can_manager_view %}
                    <h2 align="center">Список ваших сообщений для рассылки</h2>
                    <br>
                    <div class="row mt-2">
                        <div class="col m-2">
                            <a class="btn btn-outline-primary" href="{% url 'mail:message_create' %}">Добавить новое
                                сообщение</a>
                        </div>
                    </div>
                {% else %}
                    <h2 align="center">Все сообщения</h2>
                    <br>
                {% endif %}
                {% if message_list %}
                    <br>
                    <table class="table">
                        <thead>
                        <tr class="table-success">
                            <th>№</th>
                            <th>Тема сообщения</th>
                            <th>Текст сообщения</th>
                            <th>Действия с сообщением</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for message in message_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ message.message_subject }}</td>
                                <td>{{ message.message|slice:":120" }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{% url 'mail:message_view' message.pk %}"
                                           class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                        {% if not perms.mail.can_manager_view %}
                                            <a href="{% url 'mail:message_update' message.pk %}"
                                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                                            <a href="{% url 'mail:message_delete' message.pk %}"
                                               class="btn btn-sm btn-outline-danger">Удалить</a>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}<br>
                    <p align="center">Нет сообщений</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}